docker_image:                                     # [os.environ.get("BUILD_PLATFORM", "").startswith("linux") or (os.environ.get("CONFIG_VERSION", "1") == "1" and linux)]
   - quay.io/condaforge/linux-anvil-cuda:9.2      # [linux64 and (os.environ.get("BUILD_PLATFORM") == "linux-64" or os.environ.get("CONFIG_VERSION", "1") == "1")]
   - quay.io/condaforge/linux-anvil-cuda:10.2     # [linux64 and (os.environ.get("BUILD_PLATFORM") == "linux-64" or os.environ.get("CONFIG_VERSION", "1") == "1")]
   - quay.io/condaforge/linux-anvil-cuda:11.2     # [linux64 and (os.environ.get("BUILD_PLATFORM") == "linux-64" or os.environ.get("CONFIG_VERSION", "1") == "1")]

c_compiler_version:     # [linux]
  - 7                   # [linux64 or aarch64]
  - 7                   # [linux64 or aarch64]
  - 7                   # [linux64 or aarch64]
cxx_compiler_version:   # [linux]
  - 7                   # [linux64 or aarch64]
  - 7                   # [linux64 or aarch64]
  - 7                   # [linux64 or aarch64]
fortran_compiler_version: # [linux]
  - 7                     # [linux64 or aarch64]
  - 7                     # [linux64 or aarch64]
  - 7                     # [linux64 or aarch64]


cuda_compiler_version:
  - 9.2                        # [linux64]
  - 10.2                       # [linux64]
  - 11.2                       # [linux64]

cudnn:
  - 7                          # [linux64]
  - 8                          # [linux64]
  - 8                          # [linux64]

cdt_name:  # [linux]
  - cos6   # [linux64]
  - cos7   # [linux64]
  - cos7   # [linux64]

channel_sources:
  - conda-forge,defaults