docker_image:                                     # [os.environ.get("BUILD_PLATFORM", "").startswith("linux") or (os.environ.get("CONFIG_VERSION", "1") == "1" and linux)]
   - quay.io/condaforge/linux-anvil-cuda:11.2     # [linux64 and (os.environ.get("BUILD_PLATFORM") == "linux-64" or os.environ.get("CONFIG_VERSION", "1") == "1")]
   - quay.io/condaforge/linux-anvil-cos7-x86_64   # [linux64 and (os.environ.get("BUILD_PLATFORM") == "linux-64" or os.environ.get("CONFIG_VERSION", "1") == "1")]

c_compiler_version:       # [linux]
  - 10                    # [linux64 or aarch64]
  - 10                    # [linux64 or aarch64]
cxx_compiler_version:     # [linux]
  - 10                    # [linux64 or aarch64]
  - 10                    # [linux64 or aarch64]

cdt_name:                 # [linux]
  - cos7                  # [linux64]
  - cos7                  # [linux64]

cuda_compiler:
  - nvcc                  # [not win]
  - cuda-nvcc

cuda_compiler_version:
  - 11.2                  # [not win]
  - 12.0

libboost_devel:           
  - '1.82'                # [not win]             
  - '1.82'                

libtiff:
  - 4.6                   # [not win]
  - 4.6

channel_sources:
  - conda-forge
