docker_image:                                     # [os.environ.get("BUILD_PLATFORM", "").startswith("linux") or (os.environ.get("CONFIG_VERSION", "1") == "1" and linux)]
   - quay.io/condaforge/linux-anvil-cuda:11.2     # [linux64 and (os.environ.get("BUILD_PLATFORM") == "linux-64" or os.environ.get("CONFIG_VERSION", "1") == "1")]

c_compiler_version:     # [linux]
  - 7                   # [linux64 or aarch64]
cxx_compiler_version:   # [linux]
  - 7                   # [linux64 or aarch64]

cuda_compiler_version:
  - 11.2                       # [linux64 or win]

cudnn:
  - 8                          # [linux64]

cdt_name:  # [linux]
  - cos7   # [linux64]