{% if GIT_DESCRIBE_NUMBER > '0' %}
{% set version = GIT_DESCRIBE_TAG[1:] + '.dev' + GIT_DESCRIBE_NUMBER + '+rev' + GIT_DESCRIBE_HASH[1:] %}
{% else %}
{% set version = GIT_DESCRIBE_TAG[1:] %}
{% endif %}

package:
  name: cudadecon
  version: {{ version }}

source:
  path: ..

build:
  # you should export CUDA_VERSION before running conda build
  string: 'cu{{ environ.get('CUDA_VERSION') }}'
  script_env:
    - CUDA_VERSION
  
requirements:
  build:
    - {{ compiler("cxx") }} # [win]
    - ninja # [win]
    - gcc_linux-64=7.3.0 # [linux]
    - gxx_linux-64=7.3.0 # [linux]
    - cmake
    - boost-cpp
    - libtiff
    - fftw
    # - xorg-libx11 # [not win]

  run:
    {% if environ.get('CUDA_VERSION') == '10.1' %}
    - cudatoolkit=10.1 # [not osx]
    {% elif environ.get('CUDA_VERSION') == '10.0' %}
    - cudatoolkit=10.0 # [not osx]
    {% elif environ.get('CUDA_VERSION') == '9.2' %}
    - cudatoolkit=9.2 # [linux]
    {% elif environ.get('CUDA_VERSION') == '9.0' %}
    - cudatoolkit=9.0 # [not osx]
    {% endif %}
    - libtiff
    - boost-cpp
    - fftw
    # - xorg-libx11 # [not win]

test:
  commands:
    - cudaDecon --help

about:
  home: https://github.com/scopetools/cudaDecon
  license: GPL-3.0  
  summary: 'CUDA-Accelerated Richardson-Lucy Deconvolution'
  description: 'CUDA-Accelerated Richardson-Lucy Deconvolution'