# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.
# -*- mode: yaml -*-

jobs:
- job: win
  pool:
    vmImage: windows-2019
  strategy:
    matrix:
      win_64_cuda_compiler_version10.2:
        CONFIG: win_64_cuda_compiler_version10.2
        UPLOAD_PACKAGES: 'False'
      win_64_cuda_compiler_version11.0:
        CONFIG: win_64_cuda_compiler_version11.0
        UPLOAD_PACKAGES: 'False'
      win_64_cuda_compiler_version11.1:
        CONFIG: win_64_cuda_compiler_version11.1
        UPLOAD_PACKAGES: 'False'
      win_64_cuda_compiler_version11.2:
        CONFIG: win_64_cuda_compiler_version11.2
        UPLOAD_PACKAGES: 'False'
  timeoutInMinutes: 360
  variables:
    CONDA_BLD_PATH: D:\\bld\\

  steps:
    - checkout: self
      fetchDepth: 0
    - task: PythonScript@0
      displayName: 'Download Miniforge'
      inputs:
        scriptSource: inline
        script: |
          import urllib.request
          url = 'https://github.com/conda-forge/miniforge/releases/latest/download/Mambaforge-Windows-x86_64.exe'
          path = r"$(Build.ArtifactStagingDirectory)/Miniforge.exe"
          urllib.request.urlretrieve(url, path)

    - script: |
        start /wait "" %BUILD_ARTIFACTSTAGINGDIRECTORY%\Miniforge.exe /InstallationType=JustMe /RegisterPython=0 /S /D=C:\Miniforge
      displayName: Install Miniforge

    - powershell: Write-Host "##vso[task.prependpath]C:\Miniforge\Scripts"
      displayName: Add conda to PATH

    - script: |
        call activate base
        mamba.exe install "python=3.9" conda-build conda pip conda-forge-ci-setup=3 "py-lief<0.12" -c conda-forge --strict-channel-priority --yes
      displayName: Install conda-build

    - script: set PYTHONUNBUFFERED=1
      displayName: Set PYTHONUNBUFFERED

    # Configure the VM
    - script: |
        call activate base
        setup_conda_rc .\ ".\recipe" .\.ci_support\%CONFIG%.yaml
      displayName: conda-forge CI setup

    # Configure the VM.
    - script: |
        set "CI=azure"
        call activate base
        run_conda_forge_build_setup
      displayName: conda-forge build setup

    - script: |
        call activate base
        if EXIST LICENSE.txt (
          copy LICENSE.txt "recipe\\recipe-scripts-license.txt"
        )
        conda.exe build "recipe" -m .ci_support\%CONFIG%.yaml --suppress-variables
      displayName: Build recipe
      env:
        PYTHONUNBUFFERED: 1

    - script: |
        set "GIT_BRANCH=%BUILD_SOURCEBRANCHNAME%"
        set "FEEDSTOCK_NAME=%BUILD_REPOSITORY_NAME:*/=%"
        call activate base
        upload_package  .\ ".\recipe" .ci_support\%CONFIG%.yaml
      displayName: Upload package
      env:
        BINSTAR_TOKEN: $(BINSTAR_TOKEN)
      condition: and(succeeded(), not(eq(variables['UPLOAD_PACKAGES'], 'False')), not(eq(variables['Build.Reason'], 'PullRequest')))