# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.
# -*- mode: yaml -*-

jobs:
- job: linux
  pool:
    vmImage: ubuntu-latest
  strategy:
    matrix:
      linux_64_c_compiler_version11cuda_compilercuda-nvcccuda_compiler_version12.0cxx_compiler_version11:
        CONFIG: linux_64_c_compiler_version11cuda_compilercuda-nvcccuda_compiler_version12.0cxx_compiler_version11
        UPLOAD_PACKAGES: 'False'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-cos7-x86_64
      linux_64_c_compiler_version12cuda_compilernvcccuda_compiler_version11.8cxx_compiler_version12:
        CONFIG: linux_64_c_compiler_version12cuda_compilernvcccuda_compiler_version11.8cxx_compiler_version12
        UPLOAD_PACKAGES: 'False'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-cuda:11.8
  timeoutInMinutes: 360
  variables: {}

  steps:
  - checkout: self
    fetchDepth: 0
  # configure qemu binfmt-misc running.  This allows us to run docker containers
  # embedded qemu-static
  - script: |
      docker run --rm --privileged multiarch/qemu-user-static:register --reset --credential yes
      ls /proc/sys/fs/binfmt_misc/
    condition: not(startsWith(variables['CONFIG'], 'linux_64'))
    displayName: Configure binfmt_misc

  - script: |
        export CI=azure
        export flow_run_id=azure_$(Build.BuildNumber).$(System.JobAttempt)
        export remote_url=$(Build.Repository.Uri)
        export sha=$(Build.SourceVersion)
        export GIT_BRANCH=$BUILD_SOURCEBRANCHNAME
        export FEEDSTOCK_NAME=$(basename ${BUILD_REPOSITORY_NAME})
        if [[ "${BUILD_REASON:-}" == "PullRequest" ]]; then
          export IS_PR_BUILD="True"
        else
          export IS_PR_BUILD="False"
        fi
        .scripts/run_docker_build.sh
    displayName: Run docker build
    env:
      BINSTAR_TOKEN: $(BINSTAR_TOKEN)